# Generated by Django 4.0.10 on 2024-02-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Hospital's name")),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('phone_number', models.IntegerField(default='+2349012121212')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
