# Generated by Django 4.0.10 on 2024-02-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_info',
            name='phone_number',
            field=models.CharField(default='+2349012121212', max_length=14),
        ),
    ]
